### ISSUE TITLE
Add before-and-after documentation to ChangeMethodName recipes

### ISSUE THREAD

**Issue by AliSoltanianFJ** [AliSoltanianFJ/azsdk-java-rewrite-recipes-fork#97]
Need to add before-and-after code snippets to the documentation of ChangeMethodName recipes. Example:
```
# Before:
# retryOptions(new RetryOptions())
# After:
# httpRetryOptions(new RetryOptions())
- org.openrewrite.java.ChangeMethodName:
      methodPattern: com.azure.ai.translation.text.TextTranslationClientBuilder retryOptions(..)
      newMethodName: httpRetryOptions
      matchOverrides: true
```
