### ISSUE TITLE
Add before-and-after documentation to FindAndReplace recipes

### ISSUE THREAD

**Issue by AliSoltanianFJ** [AliSoltanianFJ/azsdk-java-rewrite-recipes-fork#99]
Need to add before-and-after code snippets to the documentation of FindAndReplace recipes. Example:
```
  # Recipe to replace HttpLogDetailLevel call with HttpLogOptions.HttpLogDetailLevel
  # Before:
  # HttpLogDetailLevel.BODY_AND_HEADERS
  # After:
  # HttpLogOptions.HttpLogDetailLevel.BODY_AND_HEADERS
  - org.openrewrite.text.FindAndReplace:
      find: '(?<!\.)[\w]*[\s]*HttpLogDetailLevel'
      replace: 'HttpLogOptions.HttpLogDetailLevel'
      regex: true
```
